# Generated by Django 6.0.1 on 2026-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_set_default_registration_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventinvitation',
            new_name='events_invi_status_19210a_idx',
            old_name='events_inv_status__idx',
        ),
        migrations.RenameIndex(
            model_name='eventinvitation',
            new_name='events_invi_athlete_9fe331_idx',
            old_name='events_inv_athlete__idx',
        ),
        migrations.RenameIndex(
            model_name='eventinvitation',
            new_name='events_invi_coach_i_1619b4_idx',
            old_name='events_inv_coach_s__idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='events_regi_status_87ebac_idx',
            old_name='events_reg_status__idx',
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='group_id',
            field=models.IntegerField(blank=True, help_text='ID группы, если приглашение массовое', null=True),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Персональное сообщение к приглашению', null=True),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='organization_id',
            field=models.IntegerField(blank=True, help_text='ID организации, если приглашение массовое', null=True),
        ),
    ]
