# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('1', 'Ступень 1 (6–8 лет)'), ('2', 'Ступень 2 (9–10 лет)'), ('3', 'Ступень 3 (11–12 лет)'), ('4', 'Ступень 4 (13–15 лет)'), ('5', 'Ступень 5 (16–17 лет)'), ('6', 'Ступень 6 (18–29 лет)'), ('7', 'Ступень 7 (30–39 лет)')], max_length=10)),
                ('badge', models.CharField(choices=[('bronze', 'Бронзовый'), ('silver', 'Серебряный'), ('gold', 'Золотой')], max_length=10)),
                ('completion_date', models.DateField()),
                ('protocol_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'achievements_gtoresult',
            },
        ),
        migrations.CreateModel(
            name='SportsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.CharField(choices=[('junior', 'Юный спортсмен'), ('3rd_youth', 'III юношеский'), ('2nd_youth', 'II юношеский'), ('1st_youth', 'I юношеский'), ('3rd_adult', 'III взрослый'), ('2nd_adult', 'II взрослый'), ('1st_adult', 'I взрослый'), ('cms', 'КМС'), ('ms', 'Мастер спорта'), ('msr', 'МСМК')], max_length=20)),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('document_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'achievements_rank',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('achievement_type', models.CharField(choices=[('competition', 'Соревнование'), ('gto', 'ГТО'), ('certificate', 'Сертификат')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('proof_file', models.CharField(blank=True, max_length=500)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='athletes.athleteprofile')),
            ],
            options={
                'db_table': 'achievements_achievement',
                'ordering': ['-date'],
            },
        ),
    ]
