# Generated by Django 6.0.1 on 2026-01-24 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
        ('coaches', '0003_coachinvitation'),
        ('events', '0005_rename_events_inv_status__idx_events_invi_status_19210a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='proof_file',
        ),
        migrations.AddField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото грамоты, медали и т.д. (обязательно)', null=True, upload_to='achievements/photos/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('competition', 'Соревнование'), ('gto', 'ГТО'), ('certificate', 'Сертификат'), ('medal', 'Медаль'), ('diploma', 'Грамота')], max_length=20),
        ),
        migrations.CreateModel(
            name='CoachAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название достижения или сертификата', max_length=255)),
                ('achievement_type', models.CharField(choices=[('certificate', 'Сертификат'), ('diploma', 'Диплом'), ('award', 'Награда'), ('qualification', 'Квалификация'), ('competition_result', 'Результат соревнования')], max_length=20)),
                ('date', models.DateField(help_text='Дата получения')),
                ('description', models.TextField(blank=True, help_text='Описание достижения')),
                ('photo', models.ImageField(blank=True, help_text='Фото сертификата, грамоты и т.д. (обязательно)', null=True, upload_to='coaches/achievements/photos/')),
                ('issued_by', models.CharField(blank=True, help_text='Кем выдано', max_length=255)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='coaches.coachprofile')),
                ('event', models.ForeignKey(blank=True, help_text='Связанное мероприятие (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'db_table': 'achievements_coachachievement',
                'ordering': ['-date'],
            },
        ),
    ]
