# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_committee', '0001_initial'),
        ('events', '0001_initial'),
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citypermission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='committeestaff',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.city'),
        ),
        migrations.AddField(
            model_name='committeestaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citypermission',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_committee.committeestaff'),
        ),
        migrations.AddField(
            model_name='managedevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='managedevent',
            name='managed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_committee.committeestaff'),
        ),
        migrations.AlterUniqueTogether(
            name='citypermission',
            unique_together={('staff', 'organization')},
        ),
    ]
