# Generated by Django 6.0.1 on 2026-01-24 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_committee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Уникальный код регистрации', max_length=50, unique=True)),
                ('city_name', models.CharField(help_text='Город, для которого выдан код', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Отдел/подразделение', max_length=255)),
                ('position', models.CharField(blank=True, help_text='Должность', max_length=255)),
                ('issued_by', models.CharField(blank=True, help_text='Кем выдан код', max_length=255)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_by_email', models.EmailField(blank=True, help_text='Email пользователя, использовавшего код', max_length=254, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Срок действия кода', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Код регистрации спорткомитета',
                'verbose_name_plural': 'Коды регистрации спорткомитета',
                'db_table': 'city_committee_registrationcode',
            },
        ),
    ]
