# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('education', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.city')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaches_coachprofile',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='coaches.coachprofile')),
            ],
            options={
                'db_table': 'coaches_qualification',
            },
        ),
        migrations.CreateModel(
            name='ClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_requests', to='coaches.coachprofile')),
            ],
            options={
                'db_table': 'coaches_clubrequest',
                'unique_together': {('coach', 'organization')},
            },
        ),
    ]
