# Generated by Django 6.0.1 on 2026-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrequest',
            name='age_levels',
            field=models.ManyToManyField(blank=True, to='training.agelevel'),
        ),
    ]
