# Generated by Django 6.0.1 on 2026-01-22 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_clubrequest_age_levels'),
        ('organizations', '0004_alter_organizationdocument_doc_type'),
        ('sports', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='Сообщение от директора с условиями работы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('age_levels', models.ManyToManyField(blank=True, to='training.agelevel')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='coaches.coachprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_invitations', to='organizations.organization')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
            ],
            options={
                'db_table': 'coaches_coachinvitation',
                'ordering': ['-created_at'],
                'unique_together': {('coach', 'organization')},
            },
        ),
    ]
