# Generated by Django 6.0.1 on 2026-01-24 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Имя отправителя', max_length=255)),
                ('email', models.EmailField(help_text='Email отправителя', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Телефон отправителя', max_length=20)),
                ('subject', models.CharField(choices=[('technical', 'Техническая проблема'), ('question', 'Вопрос по использованию'), ('suggestion', 'Предложение по улучшению'), ('registration', 'Проблема с регистрацией'), ('other', 'Другое')], help_text='Тема обращения', max_length=50)),
                ('message', models.TextField(help_text='Текст сообщения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('closed', 'Закрыто')], db_index=True, default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Ответ администрации')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'db_table': 'core_contactmessage',
                'ordering': ['-created_at'],
            },
        ),
    ]
