# Generated by Django 6.0.1 on 2026-01-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='role_id',
            field=models.CharField(blank=True, help_text='ID роли, с которой отправлено обращение', max_length=20),
        ),
    ]
