# Generated by Django 6.0.1 on 2026-01-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchildlink',
            name='requested_by',
            field=models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребёнок')], default='parent', max_length=20),
        ),
        migrations.AddField(
            model_name='parentchildlink',
            name='status',
            field=models.CharField(choices=[('pending_parent', 'Ожидает подтверждения от родителя'), ('pending_child', 'Ожидает подтверждения от ребёнка'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending_child', max_length=20),
        ),
    ]
