# Generated by Django 6.0.1 on 2026-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='settlement_type',
            field=models.CharField(choices=[('city', 'Город'), ('village', 'Село'), ('settlement', 'Деревня'), ('town', 'Поселок')], default='city', help_text='Тип населенного пункта', max_length=20),
        ),
    ]
