# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.traininggroup'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('athlete', 'group', 'date')},
        ),
    ]
