# Generated by Django 6.0.1 on 2026-01-16 14:15

import apps.core.models.encryption
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_or_university', models.CharField(blank=True, max_length=255)),
                ('health_group', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3)),
                ('goals', models.JSONField(default=list)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.city')),
                ('main_sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_athletes', to='sports.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'athletes_profile',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='athletes.athleteprofile')),
            ],
            options={
                'db_table': 'athletes_emergency_contact',
            },
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.JSONField(default=list)),
                ('other_conditions', apps.core.models.encryption.EncryptedTextField(blank=True)),
                ('allergies', apps.core.models.encryption.EncryptedTextField(blank=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='athletes.athleteprofile')),
            ],
            options={
                'db_table': 'athletes_medical',
            },
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('beneficiary', 'Льготник'), ('large_family', 'Многодетная семья'), ('disabled', 'ОВЗ'), ('orphan', 'Сирота'), ('none', 'Нет')], default='none', max_length=20)),
                ('document_path', models.CharField(blank=True, max_length=500)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_status', to='athletes.athleteprofile')),
            ],
            options={
                'db_table': 'athletes_socialstatus',
            },
        ),
        migrations.CreateModel(
            name='AthleteSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='athletes.athleteprofile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
            ],
            options={
                'db_table': 'athletes_specialization',
                'unique_together': {('athlete', 'sport')},
            },
        ),
    ]
