# Generated by Django 6.0.1 on 2026-01-22 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_medicalinfo_health_issues_description'),
        ('organizations', '0004_alter_organizationdocument_doc_type'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Сообщение от спортсмена')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_enrollment_assignments', to='training.traininggroup')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollment_requests', to='athletes.athleteprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollment_requests', to='organizations.organization')),
                ('sport_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='organizations.sportdirection')),
            ],
            options={
                'db_table': 'athletes_sectionenrollmentrequest',
                'ordering': ['-created_at'],
                'unique_together': {('athlete', 'sport_direction', 'status')},
            },
        ),
    ]
