# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_committee', '0001_initial'),
        ('geography', '0001_initial'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('state', 'Государственная'), ('private', 'Частная')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website', models.URLField(blank=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='geography.city')),
            ],
            options={
                'db_table': 'organizations_organization',
            },
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('adapted_restroom', models.BooleanField(default=False)),
                ('sign_language_support', models.BooleanField(default=False)),
                ('other_info', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_accessibility',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('inn', 'ИНН'), ('license', 'Лицензия'), ('charter', 'Устав')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_document',
            },
        ),
        migrations.CreateModel(
            name='PriorityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='city_committee.committeestaff')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_priority',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_verificationrequest',
            },
        ),
        migrations.CreateModel(
            name='SportDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_directions', to='organizations.organization')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
            ],
            options={
                'db_table': 'organizations_sportdirection',
                'unique_together': {('organization', 'sport')},
            },
        ),
    ]
