# Generated by Django 6.0.1 on 2026-01-16 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_clubrequest_age_levels'),
        ('organizations', '0002_remove_organization_is_verified_organization_status'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CoachMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'Архив')], default='active', max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.coachprofile')),
                ('groups', models.ManyToManyField(blank=True, to='training.traininggroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_coachmembership',
                'unique_together': {('coach', 'organization')},
            },
        ),
    ]
