# Generated by Django 6.0.1 on 2026-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_created_by_coachmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdocument',
            name='doc_type',
            field=models.CharField(choices=[('inn', 'ИНН'), ('license', 'Лицензия'), ('charter', 'Устав'), ('other', 'Другое')], max_length=20),
        ),
    ]
