# Generated by Django 6.0.1 on 2026-01-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coachinvitation'),
        ('organizations', '0004_alter_organizationdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmembership',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_memberships', to='coaches.coachprofile'),
        ),
    ]
